name: ACT_LF_POLOLU 

on:
  #push:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  led-test:
    if: contains(github.event.pull_request.labels.*.name, 'act-lf-led')
    uses: ./.github/workflows/act-lf-led.yml

  motor-test:
    needs: led-test
    if: always() && (contains(github.event.pull_request.labels.*.name, 'act-lf-motor') || needs.call-led-test.result == 'skipped')
    uses: ./.github/workflows/act-lf-motor.yml
  
  imu-test:
    needs: motor-test
    if: always() && (contains(github.event.pull_request.labels.*.name, 'act-lf-imu') || needs.call-motor-test.result == 'skipped')
    uses: ./.github/workflows/act-lf-imu.yml

  bump-test:
    needs: imu-test
    if: always() && (contains(github.event.pull_request.labels.*.name, 'act-lf-bump') || needs.call-imu-test.result == 'skipped')
    uses: ./.github/workflows/act-lf-bump.yml