name: ACT_BUMP_LF_POLOLU 

#on:
#  workflow_run:
#    workflows: ["ACT_LED_LF_POLOLU"]
#    types:
#      - completed

on:
  workflow_call:

jobs:
  setup:
    runs-on: [self-hosted, linux, lf-act-ast]
    #Strategy makes sense if there are multiple versions to test
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v5
        with:
          clean: true
          fetch-depth: 0
          submodules: recursive
      - name: Unshallow Modules
        run: |
          git submodule foreach '
            echo "Fixing submodule $name"
            git fetch --unshallow || git fetch --all
            '
      - name: Nix Setup
        id: nix
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: |
          nix develop --command true
      - name: Debug git state
        if: steps.nix.outcome == 'failure'
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: |
          git rev-parse --is-shallow-repository
          git rev-list --count HEAD

  pythonpackages:
    runs-on: [self-hosted, linux, lf-act-ast]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: |
          echo "Push detected"
          echo "$GITHUB_WORKSPACE"
          python3 -m pip install --upgrade pip
          pip3 install opencv-python numpy pandas easyocr
          python3 -c "import sys; print(sys.version)"
  
  filecleanup:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: setup
    if: always()
    steps:
      - uses: actions/checkout@v5
      - name: Copy Script
        run: cp $GITHUB_WORKSPACE/test_lf_programs/*.sh $GITHUB_WORKSPACE/lf-3pi-template/
      - name: Run Script
        working-directory: ${{ github.workspace }}/lf-3pi-template/
        run: |
          chmod +x cleanup.sh
          ./cleanup.sh

  filesetup:
    #if: github.event.workflow_run.conclusion == 'success'
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: filecleanup
    steps:
      - name: Copy Files
        working-directory: ${{ github.workspace }}
        run: |
          #ls && ls src/
          cp $GITHUB_WORKSPACE/test_lf_programs/*.py $GITHUB_WORKSPACE/lf-3pi-template
          cp $GITHUB_WORKSPACE/test_lf_programs/*.lf $GITHUB_WORKSPACE/lf-3pi-template/src
 
  compilebumptest:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [filesetup]
    steps:
      - name: Compile Bump Test
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: nix develop --command lfc src/BumpDisplay.lf
  
  flashbumptest:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [compilebumptest]
    steps:
    - name: Flashing Bump Test
      working-directory: ${{ github.workspace }}/lf-3pi-template
      run: nix develop --command picotool load -x bin/BumpDisplay.elf -f
  
  bumpright:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [flashbumptest]
    steps:
      - name: Run Test for Bump Right
        id: test1
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 test_bump_module.py
  
  bumpleft:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [bumpright]
    steps:
      - name: Run Test for Bump Left
        id: test2
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 test_bump_module.py

  bumpnone:
    runs-on: [self-hosted, linux, lf-act-ast]
    needs: [bumpleft]
    steps:
      - name: Run Test for Bump None
        id: test3
        working-directory: ${{ github.workspace }}/lf-3pi-template
        run: python3 test_bump_module.py